server:
  port: 3001

database:
  #connectionUri: host=ec2-52-51-155-48.eu-west-1.compute.amazonaws.com user=ngkiqjzertebhl password=60280cd864dc2679ba4bdb68ad74356e4323bdf8deb6516376b0dfee0d96c2aa dbname=d2m0pmql50fij4 port=5432
  #connectionUri: host=ec2-52-208-145-55.eu-west-1.compute.amazonaws.com user=syuzddgprzvlrk password=2d6cdde1b6184f780a267f1229e41c81e4a0f6fafddcd9c47aea0330f07e7131 dbname=d7kqk445q0qicg port=5432

  connectionUri: host=localhost user=postgres password=masterkey dbname=portfoyum port=5432 sslmode=disable
jwt:
  tokenKey: laksdjflkasjfwj92jfslj2qu0-9apsoifjk
  tokenExp: 720h

application:
  name: Portfoyüm
  link: http://127.0.0.1:8081/#
  sendMails: true

mail:
  smtpPort: 465
  smtpPassword: Karpuz77!
  smtpUserName: guneyin
  smtpServer: smtp.yandex.ru
  senderEmail: guneyin@ya.ru
  senderIdentity: Portföyüm

externalUrl:
  #stockSymbols: https://bigpara.hurriyet.com.tr/api/v1/hisse/list
  #stockSymbols: https://mocki.io/v1/25ae55bc-280c-43c7-948d-6db6ec3d111f
  #stockSymbolDetail: https://mocki.io/v1/1fca8d0d-506c-4113-b334-a3405aa09e93
  #stockSymbolDetail: https://bigpara.hurriyet.com.tr/api/v1/borsa/hisseyuzeysel/
  exchangeRates: https://api.exchangerate.host/%s?base=%s&symbols=TRY